return {};
-- a plugin to manage databases from nvim
-- return {
--     'kristijanhusak/vim-dadbod-ui',
--     lazy = true,
--     enabled = false, -- does not work with docker
--     dependencies = {
--         'tpope/vim-dadbod'
--     },
--     cmd = {
--         'DBUI',
--         'DBUIToggle',
--         'DBUIAddConnection',
--         'DBUIFindBuffer',
--     },
-- };
