#!/usr/bin/env bash


#######################################
# Stashes only untracked files
#######################################
function untracked() {
    git stash $@
    git stash -u
    git stash pop stash@{1}
}

untracked $@
