#!/bin/bash

declare -a PATHS
if [[ -z "$PROJECT_PATHS" ]]; then
	PATHS=("$HOME/Documents/projects" "$HOME/workspace/projects")
else
	PATHS=( $PROJECT_PATHS )
fi

if [[ $# -eq 1 ]]; then
    selected=$1
else
    selected=$({
	for path in "${PATHS[@]}"; do
		if [[ ! -d $path ]]; then
			continue
		fi
		find $path -mindepth 2 -maxdepth 2 -type d;
	done
    } | sort -u | fzf --scheme=path --height=50 --reverse --border=rounded --border-label="Choose project")
fi

if [[ -z $selected ]]; then
    exit 0
fi

selected_name=$(basename "$selected" | tr . _)
tmux_running=$(pgrep tmux)

if [[ -z $TMUX ]] && [[ -z $tmux_running ]]; then
    tmux new-session -s $selected_name -c $selected
    exit 0
fi

if ! tmux has-session -t=$selected_name 2> /dev/null; then
    tmux new-session -ds $selected_name -c $selected
fi

tmux switch-client -t $selected_name

