#!/usr/bin/env bash

# selected=$(tmux list-sessions -F '#S'| fzf)
# tmux switch-client -t $selected
#

source "$(dirname "$0")/lib/tmux-functions.sh"

err() { echo "$@" >&2; exit 1; }

delete=0

while getopts "d" OPT
do
  case "${OPT}" in
    d)       delete=1; ;;
    ??* )    err "$(basename "$0"): illegal option -- --$OPT" ;;
    ?)       err ;;
  esac
done
shift $((OPTIND - 1))

if [[ $delete -eq 0 ]]; then
    _tmux_list_session_with_last_accessed \
        | fzf --scheme=path \
            --ansi \
            --reverse \
            --border=rounded \
            --border-label="Choose session" \
            --preview="echo {} | awk '{print \$1}' | tmux-session-tree" \
            --preview-window='70%,border-left' \
        | awk '{print $1}' | xargs -I {} tmux switch-client -t {}
    exit 0
fi

_tmux_list_session_with_last_accessed \
    | fzf -m \
        --ansi \
        --scheme=path \
        --reverse \
        --border=rounded \
        --border-label="Choose sessions to delete" \
        --preview="echo {} | awk '{print \$1}' | tmux-session-tree" \
        --preview-window='70%,border-left' \
    | awk '{print $1}' | xargs -I {} tmux kill-session -t {}
