#!/usr/bin/env bash

source "$(dirname "$0")/lib/colors.sh"

tmux ls -F'#{session_id}' | while read -r session; do
    session_info=$(
        tmux ls -F'#{session_id}-#{session_name}: #{T:tree_mode_format}'\
        | grep ^"$session-"\
    )
    session_info=${session_info##"$session-"}
    session_name=$(echo "$session_info" | cut -d ':' -f 1)

    if [[ -n $1 ]] &&  [[ "$1" == "$session_name" ]]; then
        print_color "$BOLD$BLUE$session_info"
    else
        print_color "$BOLD$BLACK$session_info"
    fi
    tmux list-windows -t"$session_name" -F'#{window_id}' \
        | while read -r window_id; do
            window_info=$(
                tmux list-windows \
                    -t"$session_name" \
                    -F '#{window_id}-#{T:tree_mode_format}' \
                | grep ^"$window_id-"
            )
            window_info=${window_info##"$window_id-"}
            if [[ "$session_name" == "$1" ]]; then
                print_color "    $WHITE$BOLD$window_info"
            else
                print_color "    $IBLACK$ITALIC$window_info"
            fi
        done
done

