#!/bin/bash

# selected=$(tmux list-sessions -F '#S'| fzf)
# tmux switch-client -t $selected
#


err() { echo "$@" >&2; exit 1; }

delete=0

while getopts "d" OPT
do
  case "${OPT}" in
    d)       delete=1; ;;
    ??* )    err "$(basename "$0"): illegal option -- --$OPT" ;;
    ?)       err ;;
  esac
done
shift $((OPTIND - 1))

if [[ $delete -eq 0 ]]; then
    tmux list-sessions -F '#S' \
        | fzf --scheme=path \
            --reverse \
            --border=rounded \
            --border-label="Choose session" \
            --preview='tmux-session-tree {}' \
            --preview-window='70%,border-left' \
        | xargs -I {} tmux switch-client -t {}
    exit 0
fi

tmux list-sessions -F '#S' \
    | fzf -m \
        --scheme=path \
        --reverse \
        --border=rounded \
        --border-label="Choose sessions to delete" \
        --preview='tmux-session-tree {}' \
        --preview-window='70%,border-left' \
    | xargs -I {} tmux kill-session -t {}
